### ISSUE TITLE
Search resources everywhere, not only in active flavor

### ISSUE THREAD

**Issue by auf1r2** [niorgai/Android-Resource-Usage-Count#26]
Please add option to search resources everywhere in project.
For example in inactive flavors (*.java, *.xml files)

It will killer-feature if will show usages inside all files. Because most large projects uses 2 or more flavors. So IDEA's *find usages* is useless here.

I think it could be implemented by using Text Index search instead of Find Usages search.
For example to search any usage inside Java file it could use next pattern to search text:
`R.<type>.<resource_name>`

While for XML it could be:
`@<type>/<resource_name>`

This also automatically solves problem similar to that:
https://github.com/niorgai/Android-Resource-Usage-Count/issues/23

**Comment by niorgai** [comment]
Well..I think it's not a feature but a bug of Android Studio(IntelliJ idea).
Resource should be searched everywhere even if they are in different flavors. 
Since Android Studio(IntelliJ idea) has too much version, it's too difficult to test the search method's compatible, and that's the reason why i use the official Find Usage search.
So i think we should wait for Android Studio(IntelliJ idea) fix it.
